/**
 * src/data/curated-interferences.ts
 *
 * Manually curated polyatomic interferences that cannot be generated by the
 * two-atom combination engine — primarily homodiatomic (Ar2+, N2+, O2+)
 * and triatomic species documented in ICP-MS interference literature.
 *
 * Sources:
 *   [1] Jarvis, K.E. et al. (1992) Inductively Coupled Plasma Mass Spectrometry.
 *       Blackie Academic & Professional. ISBN 978-0-7514-0161-7.
 *   [2] Thomas, R. (2013) Practical Guide to ICP-MS, 3rd ed. CRC Press. ISBN 978-1-4665-5543-4.
 *   [3] Houk, R.S. (1986) Mass spectrometry of inductively coupled plasmas.
 *       Anal. Chem. 58, 97A-105A. https://doi.org/10.1021/ac00292a001
 *   [4] Tanner, S.D. et al. (2002) On the chemistry of ion molecule reactions.
 *       J. Anal. At. Spectrom. 17, 1361-1370. https://doi.org/10.1039/B206537A
 *
 * Access date: 2026-06-10
 *
 * IMPORTANT: All targetMass values are integer m/z (quadrupole unit resolution, 1 amu).
 * precursorAbundanceProduct is expressed as a percentage (fractional abundance product × 100).
 * Severity thresholds (half-open intervals):
 *   high   : precursorAbundanceProduct ≥ 1.0%
 *   medium : 0.01% ≤ precursorAbundanceProduct < 1.0%
 *   low    : precursorAbundanceProduct < 0.01%
 */

import type { Interference } from "../types";

/**
 * Curated interferences.
 * The engine merges these with calculated two-atom combinations before
 * building Recommendations. Deduplication is by (composition, targetMass).
 */
export const CURATED_INTERFERENCES: Interference[] = [
  // ── Homodiatomic species (not reachable by 2-element pairwise combination) ──

  // 40Ar40Ar+ → m/z 80 — major interference on 80Se
  // Product: (0.99600/100)^2 × 100 = 99.20% → high
  // Ref: Thomas [2] p.87; Jarvis [1] p.112
  {
    type: "polyatomic",
    composition: "⁴⁰Ar₂⁺",
    targetMass: 80,
    precursorElements: ["Ar"],
    precursorAbundanceProduct: 99.20,
    severity: "high",
    source: "curated",
  },

  // 40Ar38Ar+ → m/z 78 — interference on 78Se and 78Kr
  // Product: (0.99600 × 0.000632) × 100 = 0.0630% → medium
  // Ref: Thomas [2] p.87
  {
    type: "polyatomic",
    composition: "⁴⁰Ar³⁸Ar⁺",
    targetMass: 78,
    precursorElements: ["Ar"],
    precursorAbundanceProduct: 0.0630,
    severity: "medium",
    source: "curated",
  },

  // 36Ar40Ar+ → m/z 76 — interference on 76Se and 76Ge
  // Product: (0.003365 × 0.99600) × 100 = 0.335% → medium
  // Ref: Thomas [2] p.87
  {
    type: "polyatomic",
    composition: "³⁶Ar⁴⁰Ar⁺",
    targetMass: 76,
    precursorElements: ["Ar"],
    precursorAbundanceProduct: 0.335,
    severity: "medium",
    source: "curated",
  },

  // ── N2+ homodiatomic ──

  // 14N14N+ → m/z 28 — interference on 28Si
  // Product: (0.99632)^2 × 100 = 99.27% → high
  // Ref: Thomas [2] p.85
  {
    type: "polyatomic",
    composition: "¹⁴N₂⁺",
    targetMass: 28,
    precursorElements: ["N"],
    precursorAbundanceProduct: 99.27,
    severity: "high",
    source: "curated",
  },

  // 14N15N+ → m/z 29 — interference on 29Si
  // Product: (0.99632 × 0.00368) × 100 = 0.367% → medium
  {
    type: "polyatomic",
    composition: "¹⁴N¹⁵N⁺",
    targetMass: 29,
    precursorElements: ["N"],
    precursorAbundanceProduct: 0.367,
    severity: "medium",
    source: "curated",
  },

  // ── O2+ homodiatomic ──

  // 16O16O+ → m/z 32 — interference on 32S
  // Product: (0.99757)^2 × 100 = 99.51% → high
  // Ref: Thomas [2] p.85
  {
    type: "polyatomic",
    composition: "¹⁶O₂⁺",
    targetMass: 32,
    precursorElements: ["O"],
    precursorAbundanceProduct: 99.51,
    severity: "high",
    source: "curated",
  },

  // 16O18O+ → m/z 34 — interference on 34S
  // Product: (0.99757 × 0.00205) × 100 = 0.205% → medium
  {
    type: "polyatomic",
    composition: "¹⁶O¹⁸O⁺",
    targetMass: 34,
    precursorElements: ["O"],
    precursorAbundanceProduct: 0.205,
    severity: "medium",
    source: "curated",
  },

  // ── Triatomic Ar-bearing species ──

  // 40Ar16O1H+ → m/z 57 — interference on 57Fe (HNO3 matrix)
  // Product: 0.99600 × 0.99757 × 0.99988 × 100 ≈ 99.35% → high
  // Ref: Thomas [2] p.91; Houk [3]
  {
    type: "polyatomic",
    composition: "⁴⁰Ar¹⁶O¹H⁺",
    targetMass: 57,
    precursorElements: ["Ar", "O", "H"],
    precursorAbundanceProduct: 99.35,
    severity: "high",
    source: "curated",
  },

  // 40Ar14N+ → m/z 54 — interference on 54Fe and 54Cr
  // Product: 0.99600 × 0.99632 × 100 = 99.23% → high
  // Ref: Thomas [2] p.90
  {
    type: "polyatomic",
    composition: "⁴⁰Ar¹⁴N⁺",
    targetMass: 54,
    precursorElements: ["Ar", "N"],
    precursorAbundanceProduct: 99.23,
    severity: "high",
    source: "curated",
  },

  // 40Ar12C+ → m/z 52 — interference on 52Cr (organic matrices)
  // Product: 0.99600 × 0.9893 × 100 = 98.53% → high
  // Ref: Thomas [2] p.90
  {
    type: "polyatomic",
    composition: "⁴⁰Ar¹²C⁺",
    targetMass: 52,
    precursorElements: ["Ar", "C"],
    precursorAbundanceProduct: 98.53,
    severity: "high",
    source: "curated",
  },

  // 38Ar16O+ → m/z 54 — additional interference on 54Fe/54Cr
  // Product: 0.000632 × 0.99757 × 100 = 0.0630% → medium
  {
    type: "polyatomic",
    composition: "³⁸Ar¹⁶O⁺",
    targetMass: 54,
    precursorElements: ["Ar", "O"],
    precursorAbundanceProduct: 0.0630,
    severity: "medium",
    source: "curated",
  },

  // 40Ar2 16O+ triatomic → m/z 96 — interference on 96Mo, 96Ru, 96Zr
  // Product: (0.99600)^2 × 0.99757 × 100 = 99.16% → high
  // Ref: Thomas [2] p.92
  {
    type: "polyatomic",
    composition: "⁴⁰Ar₂¹⁶O⁺",
    targetMass: 96,
    precursorElements: ["Ar", "O"],
    precursorAbundanceProduct: 99.16,
    severity: "high",
    source: "curated",
  },
];
